apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: football-bets
  namespace: football-bets
spec:
  hosts:
  - "*"
  gateways:
  - football-bets
  http:
  - route:
    - destination:
        port:
          number: 9090
        host: bets.football-bets.svc.cluster.local
