apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: football-bets
  namespace: football-bets
spec:
  gateways:
    - football-bets
  hosts:
    - football.com
  http:
    - match:
        - uri:
            prefix: /bets
      route:
        - destination:
            host: bets.football-bets.svc.cluster.local
            port:
              number: 9090