apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: football-bets
  namespace: football-bets
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - football.com
      port:
        name: http
        number: 80
        protocol: HTTP
